### ISSUE TITLE
npm i macaca-chromedriver --save-dev  安装失败

### ISSUE THREAD

**Issue by flyoverGu** [macacajs/macaca-chromedriver#10]
```
>> chromedriver cdn url: http://oss.npm.taobao.org/dist/chromedriver/2.20/chromedriver_mac32.zip
/Users/flyover/node_modules/macaca-chromedriver/node_modules/jszip/lib/zipEntries.js:149
                throw new Error("Can't find end of central directory : is this a zip file ? " +
                ^

Error: Can't find end of central directory : is this a zip file ? If it is, see http://stuk.github.io/jszip/documentation/howto/read_zip.html
    at Object.ZipEntries.readEndOfCentral (/Users/flyover/node_modules/macaca-chromedriver/node_modules/jszip/lib/zipEntries.js:149:23)
    at Object.ZipEntries.load (/Users/flyover/node_modules/macaca-chromedriver/node_modules/jszip/lib/zipEntries.js:215:14)
    at Object.ZipEntries (/Users/flyover/node_modules/macaca-chromedriver/node_modules/jszip/lib/zipEntries.js:21:14)
    at Object.module.exports [as load] (/Users/flyover/node_modules/macaca-chromedriver/node_modules/jszip/lib/load.js:11:18)
    at Object.JSZip (/Users/flyover/node_modules/macaca-chromedriver/node_modules/jszip/lib/index.js:39:14)
    at UnZipStream._flush (/Users/flyover/node_modules/macaca-chromedriver/lib/install.js:45:13)
    at UnZipStream.<anonymous> (_stream_transform.js:118:12)
    at UnZipStream.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at UnZipStream.emit (events.js:166:7)
```

http://oss.npm.taobao.org/dist/chromedriver/2.20/chromedriver_mac32.zip 地址换了吗？

**Comment by xudafeng** [comment]
cnpm 或者exports源，看社区分享
